since the outer process calls this script once per incomplete attempt assuming the mirrors are done one at a time, we make the script idempotent once, and let it keep calling, assuming it will just error out once per mirror at this point

diff --git a/garia2c b/garia2c
--- a/garia2c
+++ b/garia2c
@@ -3,28 +3,50 @@
 set -x
 DISTDIR="$1"
 FILE="$2"
-URI="$3"
-shift 3
+# Determine an idempotent temp file
+: tempdir is ${TMPDIR:=/tmp}
 
-# the mirrors: $@
-MIRRORS=( $@ )
+FILE_HASH=$(echo -n "$FILE" | md5sum | cut -d ' ' -f 1)
+TMPFILE="$TMPDIR/$FILE_HASH"
 
-pushd "$DISTDIR"
+# If the temp file does not exist, create it
+[[ ! -f "$TMPFILE" ]] && {
+    URI="$3"
+    shift 3
+    # the rest of the arguments are the mirrors
 
-# start building the aria2c command
-CMD="aria2c -c -j 15 -s 15 -x 15 --remote-time --http-accept-gzip --uri-selector=adaptive  -d $DISTDIR -o $FILE"
-CMD=( $CMD )
+    : the mirrors: $@
+    MIRRORS=( $@ )
 
-# get the first mirror
-FIRST_MIRROR=${MIRRORS[0]}
+    pushd "$DISTDIR"
 
-# for each mirror starting from index 1
-for ((i=1; i<${#MIRRORS[@]}; i++)); do
-    # replace the first mirror in the URI with the current mirror
-    MIRROR_URI=$(echo "$URI" | sed "s#$FIRST_MIRROR#${MIRRORS[$i]}#g")
-    # add the mirror URI to the command
-    CMD+=("$MIRROR_URI")
-done
+    # start building the aria2c command
+    CMD="aria2c -c -j 15 -s 15 -x 15 --remote-time --http-accept-gzip --uri-selector=adaptive  -d $DISTDIR -o $FILE"
+    CMD=( $CMD )
 
-# execute the aria2c command
-"${CMD[@]}"
+    # find the index of the mirror that is being used as the prefix of the URI
+    key_index=0
+    for index in "${!MIRRORS[@]}"; do
+        [[ "$URI" == "${MIRRORS[$index]}"* ]] && key_index=$index && break
+    done
+
+    # for each mirror
+    for index in "${!MIRRORS[@]}"; do
+        # if the current index is not equal to the key_index
+        [[ $index -ne $key_index ]] && {
+            # replace the key mirror in the URI with the current mirror
+            MIRROR_URI=$(echo "$URI" | sed "s#${MIRRORS[$key_index]}#${MIRRORS[$index]}#g")
+            # add the mirror URI to the command
+            CMD+=("$MIRROR_URI")
+        }
+    done
+
+    # Store the aria2c command in the temp file
+    echo "${CMD[@]}" > "$TMPFILE"
+}
+
+# Execute the aria2c command
+. "$TMPFILE" && rm "$TMPFILE" || {
+    echo "Failed to download $FILE into $DISTDIR from $URI using aria2c in $TMPFILE" with exit code ${errcode:=$?} >&2
+    exit $errcode
+}
